### ISSUE TITLE
Replace image of Reachy's back IO

### ISSUE THREAD

**Issue by matthieu-lapeyre** [pollen-robotics/reachy-2019#62]
Reachy installation is out-dated https://pollen-robotics.github.io/reachy-docs/docs/getting-started/install-your-robot/

We should update the last photo with one of these: https://photos.app.goo.gl/CQaccomnM4KLzNTSA

**Comment by pierre-rouanet** [comment]
Fixed in https://github.com/pollen-robotics/reachy-docs/commit/1c73e00765ded725ee17b622744856451cc0ae5c
